name: Validacion de Sintaxis y Codigo Seguro

on: [push, pull_request]

jobs:
  analisis-codigo:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio en el contenedor
      uses: actions/checkout@v3

    - name: Configurar Entorno de Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Validar sintaxis de scripts de Ciberdefensa
      run: |
        python -m compileall .